# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16e224d510545dd8f22f01fe25064456d270633f593d7e565d90a73e620944f614a74094b99c3194fad8b8ab9a660ea1d372268a6a81d093dfc961a03749262c

test:
  secret_key_base: 20db8c985eae3f3c069d84b4088e48ec36be631b15df10c5e0eca4f47328544b033deb61894e1caae9772f375e44eec1c8898a7f054e1025033ef1c6abd4c67f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
